RookieShop.FrontStore/Models/HomeViewModel.cs
using RookieShop.ProductCatalog.ViewModels;
using RookieShop.Shared.Models;

namespace RookieShop.FrontStore.Models;

public class HomeViewModel
{
    public IEnumerable<ProductDto> FeaturedProducts { get; set; } = null!;
    public Pagination<ProductDto> ProductPage { get; set; } = null!;
    public IEnumerable<CategoryDto> Categories { get; set; } = null!;
}

RookieShop.FrontStore/Components/ProductCardViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using RookieShop.FrontStore.Models.Shared.Components;
using RookieShop.ProductCatalog.ViewModels;

namespace RookieShop.FrontStore.Components;

[ViewComponent(Name = "ProductCard")]
public class ProductCardViewComponent : ViewComponent
{
    public IViewComponentResult Invoke(ProductDto product, bool showFeaturedTag)
    {
        return View(new ProductCardViewModel
        {
            Product = product,
            ShowFeaturedTag = showFeaturedTag
        });
    }
}

RookieShop.FrontStore/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using RookieShop.FrontStore.Models;
using RookieShop.FrontStore.Modules.ProductCatalog.Abstractions;

namespace RookieShop.FrontStore.Controllers;

public class HomeController : Controller
{
    private readonly IProductService _productService;
    private readonly ICategoryService _categoryService;
    
    public HomeController(IProductService productService, ICategoryService categoryService)
    {
        _productService = productService;
        _categoryService = categoryService;
    }

    public async Task<IActionResult> Index(CancellationToken cancellationToken)
    {
        var featuredProductsTask = _productService.GetFeaturedProductsAsync(4, cancellationToken);
        var productPageTask = _productService.GetProductsAsync(1, 8, cancellationToken);
        var categoriesTask = _categoryService.GetCategoriesAsync(cancellationToken);
        
        await Task.WhenAll(featuredProductsTask, productPageTask, categoriesTask);
        
        var featuredProducts = featuredProductsTask.Result;
        var productPage = productPageTask.Result;
        var categories = categoriesTask.Result;
        
        return View(new HomeViewModel
        {
            FeaturedProducts = featuredProducts,
            ProductPage = productPage,
            Categories = categories
        });
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

RookieShop.FrontStore/Controllers/ProductsController.cs
using Microsoft.AspNetCore.Mvc;
using RookieShop.FrontStore.Models;
using RookieShop.FrontStore.Models.Products;
using RookieShop.FrontStore.Modules.ProductCatalog.Abstractions;

namespace RookieShop.FrontStore.Controllers;

public class ProductsController : Controller
{
    private readonly IProductService _productService;
    private readonly ICategoryService _categoryService;
    private readonly IReviewService _reviewService;
    private readonly ILogger<ProductsController> _logger;

    public ProductsController(IProductService productService, ICategoryService categoryService, IReviewService reviewService, ILogger<ProductsController> logger)
    {
        _productService = productService;
        _categoryService = categoryService;
        _reviewService = reviewService;
        _logger = logger;
    }

    public async Task<IActionResult> Index(int? pageNumber, CancellationToken cancellationToken)
    {
        var productPage = await _productService.GetProductsAsync(int.Max(pageNumber ?? 1, 1), 8, cancellationToken);

        return View(new ProductsViewModel
        {
            ProductPage = productPage
        });
    }
    
    public async Task<IActionResult> ProductsByCategory(int id, int? pageNumber, CancellationToken cancellationToken)
    {
        var categoryTask = _categoryService.GetCategoryByIdAsync(id, cancellationToken);
        var productPageTask = _productService.GetProductsByCategoryIdAsync(id, int.Max(pageNumber ?? 1, 1), 12, cancellationToken);
        
        await Task.WhenAll(categoryTask, productPageTask);
        
        var category = categoryTask.Result;
        var productPage = productPageTask.Result;

        return View(new ProductsByCategoryViewModel
        {
            Category = category,
            ProductPage = productPage
        });
    }

    public async Task<IActionResult> ProductDetails(string id, int? pageNumber,
        CancellationToken cancellationToken)
    {
        var productTask = _productService.GetProductBySkuAsync(id, cancellationToken);
        var reviewPageTask = _reviewService.GetReviewsBySkuAsync(id, int.Max(pageNumber ?? 1, 1), 10, cancellationToken);
        
        await Task.WhenAll(productTask, reviewPageTask);
        
        var product = productTask.Result;
        var reviewPage = reviewPageTask.Result;

        return View(new ProductDetailsViewModel
        {
            Product = product,
            ReviewPage = reviewPage
        });
    }

    public async Task<IActionResult> ProductsSemantic(string? semantic, int? pageNumber, int? pageSize,
        CancellationToken cancellationToken)
    {
        semantic ??= "";
        var productPage = await _productService.GetProductsSemanticAsync(semantic, pageNumber ?? 1, pageSize ?? 12, cancellationToken);

        return View(new ProductsSemanticViewModel
        {
            Semantic = semantic,
            ProductPage = productPage
        });
    }
}

RookieShop.FrontStore/Views/Home/Index.cshtml
@model HomeViewModel

@{
  ViewData["Title"] = "Home";
}

<section class="bg-gray-50 py-8 antialiased dark:bg-gray-900 md:py-16">
  <div class="mx-auto max-w-screen-xl px-4 2xl:px-0">
    <div class="mb-4 flex items-center justify-between gap-4 md:mb-8">
      <h2 class="text-xl font-semibold text-gray-900 dark:text-white sm:text-2xl">Categories</h2>
    </div>

    <div class="grid gap-4 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4">
      @foreach (var category in Model.Categories)
      {
        <a asp-controller="Products" asp-action="ProductsByCategory" asp-route-id="@category.Id" class="flex justify-between items-center rounded-lg border border-gray-200 bg-white px-4 py-2 hover:bg-gray-50 dark:border-gray-700 dark:bg-gray-800 dark:hover:bg-gray-700">
          <span class="text-sm font-medium text-gray-900 dark:text-white">@category.Name</span>
          <span class="text-sm font-medium text-gray-900 dark:text-white">(@category.ProductCount)</span>
        </a>
      }
    </div>
  </div>
</section>

<section class="bg-gray-50 py-8 antialiased dark:bg-gray-900 md:py-12">
  <div class="mx-auto max-w-screen-xl px-4 2xl:px-0">
    <div class="mb-4 items-end justify-between space-y-4 sm:flex sm:space-y-0 md:mb-8">
      <div>
        <h2 class="mt-3 text-xl font-semibold text-gray-900 dark:text-white sm:text-2xl">Featured Products</h2>
      </div>
    </div>
    
    <div class="mb-4 grid gap-4 sm:grid-cols-2 md:mb-8 lg:grid-cols-3 xl:grid-cols-4">
      @foreach (var product in Model.FeaturedProducts)
      {
        @await Component.InvokeAsync("ProductCard", new { product = product, showFeaturedTag = true })
      }
    </div>
  </div>
</section>

<section class="bg-gray-50 py-8 antialiased dark:bg-gray-900 md:py-12">
  <div class="mx-auto max-w-screen-xl px-4 2xl:px-0">
    <div class="mb-4 items-end justify-between space-y-4 sm:flex sm:space-y-0 md:mb-8">
      <div>
        <h2 class="mt-3 text-xl font-semibold text-gray-900 dark:text-white sm:text-2xl">Products</h2>
      </div>
    </div>
    
    <div class="mb-4 grid gap-4 sm:grid-cols-2 md:mb-8 lg:grid-cols-3 xl:grid-cols-4">
      @foreach (var product in Model.ProductPage.Items)
      {
        @await Component.InvokeAsync("ProductCard", new { product = product, showFeaturedTag = false })
      }
    </div>
    
    <div class="w-full text-center">
      <a asp-controller="Products" asp-action="Index" role="button" class="rounded-lg border border-gray-200 bg-white px-5 py-2.5 text-sm font-medium text-gray-900 hover:bg-gray-100 hover:text-primary-700 focus:z-10 focus:outline-none focus:ring-4 focus:ring-gray-100 dark:border-gray-600 dark:bg-gray-800 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white dark:focus:ring-gray-700">Show more</a>
    </div>
  </div>
</section>