RookieShop.FrontStore/Models/Shared/Components/AddToCartButtonViewModel.cs
using RookieShop.ProductCatalog.ViewModels;

namespace RookieShop.FrontStore.Models.Shared.Components;

public class AddToCartButtonViewModel
{
    public string? ContinueUrl { get; set; }

    public ProductDto Product { get; set; } = null!;
}

RookieShop.FrontStore/Models/Shared/Components/HeaderViewModel.cs
using RookieShop.Shopping.ViewModels;

namespace RookieShop.FrontStore.Models.Shared.Components;

public class HeaderViewModel
{
    public CartDto? Cart { get; set; }
}

RookieShop.FrontStore/Models/Shared/Components/PaginationViewModel.cs
namespace RookieShop.FrontStore.Models.Shared.Components;

public class PaginationViewModel
{
    public long Count { get; set; }
    public int PageNumber { get; set; }
    public int PageSize { get; set; }
    public Dictionary<string, string> OtherParams { get; set; } = null!;
}

RookieShop.FrontStore/Models/Shared/Components/ProductCardViewModel.cs
using RookieShop.ProductCatalog.ViewModels;

namespace RookieShop.FrontStore.Models.Shared.Components;

public class ProductCardViewModel
{
    public ProductDto Product { get; set; } = null!;
    public bool ShowFeaturedTag { get; set; }
}

RookieShop.FrontStore/Models/Shared/Components/RatingStartsViewModel.cs
namespace RookieShop.FrontStore.Models.Shared.Components;

public class RatingStartsViewModel
{
    public int Stars { get; set; }
    public bool IsBig { get; set; } 
}

RookieShop.FrontStore/Components/HeaderViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using RookieShop.FrontStore.Models.Shared.Components;

namespace RookieShop.FrontStore.Components;

[ViewComponent(Name = "Header")]
public class HeaderViewComponent : ViewComponent
{
    public IViewComponentResult Invoke()
    {
        return View(new HeaderViewModel
        {
            Cart = ViewBag.Cart
        });
    }
}

RookieShop.FrontStore/Views/Shared/_Layout.cshtml
@inject IHttpContextAccessor HttpContextAccessor

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - RookieShop</title>
    <link rel="stylesheet" href="~/css/styles.css" asp-append-version="true"/>
    <script>
        if (localStorage.getItem('color-theme') === 'dark' || (!('color-theme' in localStorage) && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
            document.documentElement.classList.add('dark');
        } else {
            document.documentElement.classList.remove('dark')
        }
    </script>
</head>
<body>
    @await Component.InvokeAsync("Header", new { cancellationToken = HttpContextAccessor.HttpContext?.RequestAborted })
    
    <main role="main" class="h-screen bg-gray-50 dark:bg-gray-900">
        @RenderBody()
    </main>
    <script src="~/js/flowbite.min.js"></script>
    <script type="text/javascript">
        initFlowbite();

        const themeToggleDarkIcon = document.getElementById('theme-toggle-dark-icon');
        const themeToggleLightIcon = document.getElementById('theme-toggle-light-icon');

        // Change the icons inside the button based on previous settings
        if (localStorage.getItem('color-theme') === 'dark' || (!('color-theme' in localStorage) && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
            themeToggleLightIcon.classList.remove('hidden');
        } else {
            themeToggleDarkIcon.classList.remove('hidden');
        }

        const themeToggleBtn = document.getElementById('theme-toggle');

        themeToggleBtn.addEventListener('click', function() {

            // toggle icons inside button
            themeToggleDarkIcon.classList.toggle('hidden');
            themeToggleLightIcon.classList.toggle('hidden');

            // if set via local storage previously
            if (localStorage.getItem('color-theme')) {
                if (localStorage.getItem('color-theme') === 'light') {
                    document.documentElement.classList.add('dark');
                    localStorage.setItem('color-theme', 'dark');
                } else {
                    document.documentElement.classList.remove('dark');
                    localStorage.setItem('color-theme', 'light');
                }

                // if NOT set via local storage previously
            } else {
                if (document.documentElement.classList.contains('dark')) {
                    document.documentElement.classList.remove('dark');
                    localStorage.setItem('color-theme', 'light');
                } else {
                    document.documentElement.classList.add('dark');
                    localStorage.setItem('color-theme', 'dark');
                }
            }

        });
    </script>
    @await RenderSectionAsync("Scripts", required: false)
    </body>
</html>