RookieShop.FrontStore/Models/Shared/Components/AddToCartButtonViewModel.cs
using RookieShop.ProductCatalog.ViewModels;

namespace RookieShop.FrontStore.Models.Shared.Components;

public class AddToCartButtonViewModel
{
    public string? ContinueUrl { get; set; }

    public ProductDto Product { get; set; } = null!;
}

RookieShop.FrontStore/Models/Shared/Components/HeaderViewModel.cs
using RookieShop.Shopping.ViewModels;

namespace RookieShop.FrontStore.Models.Shared.Components;

public class HeaderViewModel
{
    public CartDto? Cart { get; set; }
}

RookieShop.FrontStore/Models/Shared/Components/PaginationViewModel.cs
namespace RookieShop.FrontStore.Models.Shared.Components;

public class PaginationViewModel
{
    public long Count { get; set; }
    public int PageNumber { get; set; }
    public int PageSize { get; set; }
    public Dictionary<string, string> OtherParams { get; set; } = null!;
}

RookieShop.FrontStore/Models/Shared/Components/ProductCardViewModel.cs
using RookieShop.ProductCatalog.ViewModels;

namespace RookieShop.FrontStore.Models.Shared.Components;

public class ProductCardViewModel
{
    public ProductDto Product { get; set; } = null!;
    public bool ShowFeaturedTag { get; set; }
}

RookieShop.FrontStore/Models/Shared/Components/RatingStartsViewModel.cs
namespace RookieShop.FrontStore.Models.Shared.Components;

public class RatingStartsViewModel
{
    public int Stars { get; set; }
    public bool IsBig { get; set; } 
}

RookieShop.FrontStore/Components/AddToCartButtonViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using RookieShop.FrontStore.Models.Shared.Components;
using RookieShop.ProductCatalog.ViewModels;

namespace RookieShop.FrontStore.Components;

[ViewComponent(Name = "AddToCartButton")]
public class AddToCartButtonViewComponent : ViewComponent
{
    public IViewComponentResult Invoke(ProductDto product, string? continueUrl)
    {
        return View(new AddToCartButtonViewModel
        {
            Product = product,
            ContinueUrl = continueUrl
        });
    }
}

RookieShop.FrontStore/Components/HeaderViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using RookieShop.FrontStore.Models.Shared.Components;

namespace RookieShop.FrontStore.Components;

[ViewComponent(Name = "Header")]
public class HeaderViewComponent : ViewComponent
{
    public IViewComponentResult Invoke()
    {
        return View(new HeaderViewModel
        {
            Cart = ViewBag.Cart
        });
    }
}

RookieShop.FrontStore/Components/PaginationViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using RookieShop.FrontStore.Models.Shared.Components;

namespace RookieShop.FrontStore.Components;

[ViewComponent(Name = "Pagination")]
public class PaginationViewComponent : ViewComponent
{
    public IViewComponentResult Invoke(long count, int pageNumber, int pageSize, Dictionary<string, string>? otherParams = null)
    {
        return View(new PaginationViewModel
        {
            Count = count,
            PageNumber = pageNumber,
            PageSize = pageSize,
            OtherParams = otherParams ?? new Dictionary<string, string>()
        });
    }
}

RookieShop.FrontStore/Components/ProductCardViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using RookieShop.FrontStore.Models.Shared.Components;
using RookieShop.ProductCatalog.ViewModels;

namespace RookieShop.FrontStore.Components;

[ViewComponent(Name = "ProductCard")]
public class ProductCardViewComponent : ViewComponent
{
    public IViewComponentResult Invoke(ProductDto product, bool showFeaturedTag)
    {
        return View(new ProductCardViewModel
        {
            Product = product,
            ShowFeaturedTag = showFeaturedTag
        });
    }
}

RookieShop.FrontStore/Components/RatingStarsViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using RookieShop.FrontStore.Models.Shared.Components;

namespace RookieShop.FrontStore.Components;

[ViewComponent(Name = "RatingStars")]
public class RatingStarsViewComponent : ViewComponent
{
    public IViewComponentResult Invoke(int stars, bool isBig)
    {
        return View(new RatingStartsViewModel
        {
            Stars = stars,
            IsBig = isBig
        });
    }
}

RookieShop.FrontStore/Views/Shared/Components/ProductCard/Default.cshtml
@using RookieShop.FrontStore.Modules.ImageGallery
@model RookieShop.FrontStore.Models.Shared.Components.ProductCardViewModel
@inject ImageGalleryUrlResolver ImageGalleryUrlResolver

<div class="flex flex-col justify-between rounded-lg border border-gray-200 bg-white p-6 shadow-sm dark:border-gray-700 dark:bg-gray-800">
  <div>
    <div class="w-full aspect-square">
      <a href="/Products/ProductDetails/@Model.Product.Sku">
        <img class="mx-auto h-full dark:hidden aspect-square object-cover" src="@ImageGalleryUrlResolver.ResolveImageUrl(Model.Product.PrimaryImageId)" alt="@Model.Product.Name"/>
        <img class="mx-auto hidden h-full dark:block aspect-square object-cover" src="@ImageGalleryUrlResolver.ResolveImageUrl(Model.Product.PrimaryImageId)" alt="@Model.Product.Name"/></a>
    </div>

    <div class="pt-6 h-fit flex flex-col justify-between">
      <a href="/Products/ProductDetails/@Model.Product.Sku" class="text-lg font-semibold leading-tight text-gray-900 hover:underline dark:text-white truncate">@Model.Product.Name</a>

      <div class="mt-2 flex items-center gap-2">
        @await Component.InvokeAsync("RatingStars", new { stars = (int)Math.Round(Model.Product.Rating.Score), isBig = false })

        <p class="text-sm font-medium text-gray-900 dark:text-white">@Model.Product.Rating.Score</p>
        <p class="text-sm font-medium text-gray-500 dark:text-gray-400">(@Model.Product.Rating.Count)</p>
      </div>

      <div class="mt-2 flex items-center gap-2">
        <p class="text-sm font-medium text-gray-900 dark:text-white">Availability:</p>
        <p class="text-sm font-medium text-gray-500 dark:text-gray-400">@Model.Product.AvailableQuantity units</p>
      </div>

      @if (Model.Product.IsFeatured && Model.ShowFeaturedTag)
      {
        <ul class="mt-2 flex items-center gap-4">
          <li class="flex items-center gap-2">
            <svg class="h-4 w-4 text-gray-500 dark:text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
              <path
                stroke="currentColor"
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                d="m7.171 12.906-2.153 6.411 2.672-.89 1.568 2.34 1.825-5.183m5.73-2.678 2.154 6.411-2.673-.89-1.568 2.34-1.825-5.183M9.165 4.3c.58.068 1.153-.17 1.515-.628a1.681 1.681 0 0 1 2.64 0 1.68 1.68 0 0 0 1.515.628 1.681 1.681 0 0 1 1.866 1.866c-.068.58.17 1.154.628 1.516a1.681 1.681 0 0 1 0 2.639 1.682 1.682 0 0 0-.628 1.515 1.681 1.681 0 0 1-1.866 1.866 1.681 1.681 0 0 0-1.516.628 1.681 1.681 0 0 1-2.639 0 1.681 1.681 0 0 0-1.515-.628 1.681 1.681 0 0 1-1.867-1.866 1.681 1.681 0 0 0-.627-1.515 1.681 1.681 0 0 1 0-2.64c.458-.361.696-.935.627-1.515A1.681 1.681 0 0 1 9.165 4.3ZM14 9a2 2 0 1 1-4 0 2 2 0 0 1 4 0Z"/>
            </svg>
            <p class="text-sm font-medium text-gray-500 dark:text-gray-400">Best Seller</p>
          </li>
        </ul>
      }
    </div>
  </div>

  <div class="mt-6 flex items-center justify-between gap-4">
    <p class="text-lg font-extrabold leading-tight text-gray-900 dark:text-white">$@Model.Product.Price.ToString("F2")</p>

    @await Component.InvokeAsync("AddToCartButton", new { product = Model.Product })
  </div>
</div>