RookieShop.FrontStore/Models/Products/ProductDetailsViewModel.cs
using RookieShop.ProductCatalog.ViewModels;
using RookieShop.Shared.Models;

namespace RookieShop.FrontStore.Models.Products;

public class ProductDetailsViewModel
{
    public ProductDto Product { get; set; } = null!;
    
    public Pagination<ReviewDto> ReviewPage { get; set; } = null!;
}

RookieShop.FrontStore/Models/Products/ProductsByCategoryViewModel.cs
using RookieShop.ProductCatalog.ViewModels;
using RookieShop.Shared.Models;

namespace RookieShop.FrontStore.Models.Products;

public class ProductsByCategoryViewModel
{
    public CategoryDto Category { get; set; } = null!;
    public Pagination<ProductDto> ProductPage { get; set; } = null!;
}

RookieShop.FrontStore/Models/Products/ProductsSemanticViewModel.cs
using RookieShop.ProductCatalog.ViewModels;
using RookieShop.Shared.Models;

namespace RookieShop.FrontStore.Models.Products;

public class ProductsSemanticViewModel
{
    public string Semantic { get; set; } = null!;
    
    public Pagination<ProductDto> ProductPage { get; set; } = null!;
}

RookieShop.FrontStore/Models/ProductsByCategoryViewModel.cs
using RookieShop.FrontStore.Models.Shared.Application;

namespace RookieShop.FrontStore.Models;

public class ProductsByCategoryViewModel
{
    public CategoryDto Category { get; set; } = null!;
    public Pagination<ProductDto> ProductPage { get; set; } = null!;
}

RookieShop.FrontStore/Models/ProductsViewModel.cs
using RookieShop.ProductCatalog.ViewModels;
using RookieShop.Shared.Models;

namespace RookieShop.FrontStore.Models;

public class ProductsViewModel
{
    public Pagination<ProductDto> ProductPage { get; set; } = null!;
}

RookieShop.FrontStore/Components/PaginationViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using RookieShop.FrontStore.Models.Shared.Components;

namespace RookieShop.FrontStore.Components;

[ViewComponent(Name = "Pagination")]
public class PaginationViewComponent : ViewComponent
{
    public IViewComponentResult Invoke(long count, int pageNumber, int pageSize, Dictionary<string, string>? otherParams = null)
    {
        return View(new PaginationViewModel
        {
            Count = count,
            PageNumber = pageNumber,
            PageSize = pageSize,
            OtherParams = otherParams ?? new Dictionary<string, string>()
        });
    }
}

RookieShop.FrontStore/Components/ProductCardViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using RookieShop.FrontStore.Models.Shared.Components;
using RookieShop.ProductCatalog.ViewModels;

namespace RookieShop.FrontStore.Components;

[ViewComponent(Name = "ProductCard")]
public class ProductCardViewComponent : ViewComponent
{
    public IViewComponentResult Invoke(ProductDto product, bool showFeaturedTag)
    {
        return View(new ProductCardViewModel
        {
            Product = product,
            ShowFeaturedTag = showFeaturedTag
        });
    }
}

RookieShop.FrontStore/Controllers/ProductsController.cs
using Microsoft.AspNetCore.Mvc;
using RookieShop.FrontStore.Models;
using RookieShop.FrontStore.Models.Products;
using RookieShop.FrontStore.Modules.ProductCatalog.Abstractions;

namespace RookieShop.FrontStore.Controllers;

public class ProductsController : Controller
{
    private readonly IProductService _productService;
    private readonly ICategoryService _categoryService;
    private readonly IReviewService _reviewService;
    private readonly ILogger<ProductsController> _logger;

    public ProductsController(IProductService productService, ICategoryService categoryService, IReviewService reviewService, ILogger<ProductsController> logger)
    {
        _productService = productService;
        _categoryService = categoryService;
        _reviewService = reviewService;
        _logger = logger;
    }

    public async Task<IActionResult> Index(int? pageNumber, CancellationToken cancellationToken)
    {
        var productPage = await _productService.GetProductsAsync(int.Max(pageNumber ?? 1, 1), 8, cancellationToken);

        return View(new ProductsViewModel
        {
            ProductPage = productPage
        });
    }
    
    public async Task<IActionResult> ProductsByCategory(int id, int? pageNumber, CancellationToken cancellationToken)
    {
        var categoryTask = _categoryService.GetCategoryByIdAsync(id, cancellationToken);
        var productPageTask = _productService.GetProductsByCategoryIdAsync(id, int.Max(pageNumber ?? 1, 1), 12, cancellationToken);
        
        await Task.WhenAll(categoryTask, productPageTask);
        
        var category = categoryTask.Result;
        var productPage = productPageTask.Result;

        return View(new ProductsByCategoryViewModel
        {
            Category = category,
            ProductPage = productPage
        });
    }

    public async Task<IActionResult> ProductDetails(string id, int? pageNumber,
        CancellationToken cancellationToken)
    {
        var productTask = _productService.GetProductBySkuAsync(id, cancellationToken);
        var reviewPageTask = _reviewService.GetReviewsBySkuAsync(id, int.Max(pageNumber ?? 1, 1), 10, cancellationToken);
        
        await Task.WhenAll(productTask, reviewPageTask);
        
        var product = productTask.Result;
        var reviewPage = reviewPageTask.Result;

        return View(new ProductDetailsViewModel
        {
            Product = product,
            ReviewPage = reviewPage
        });
    }

    public async Task<IActionResult> ProductsSemantic(string? semantic, int? pageNumber, int? pageSize,
        CancellationToken cancellationToken)
    {
        semantic ??= "";
        var productPage = await _productService.GetProductsSemanticAsync(semantic, pageNumber ?? 1, pageSize ?? 12, cancellationToken);

        return View(new ProductsSemanticViewModel
        {
            Semantic = semantic,
            ProductPage = productPage
        });
    }
}

RookieShop.FrontStore/Views/Products/Index.cshtml
@model ProductsViewModel

@{
    ViewData["Title"] = "Product Catalog";
}

<section class="bg-gray-50 py-8 antialiased dark:bg-gray-900 md:py-12">
    <div class="mx-auto max-w-screen-xl px-4 2xl:px-0">
        <div class="mb-4 items-end justify-between space-y-4 sm:flex sm:space-y-0 md:mb-8">
            <div>
                <h2 class="mt-3 text-xl font-semibold text-gray-900 dark:text-white sm:text-2xl">Products</h2>
            </div>
        </div>

        <div class="mb-4 grid gap-4 sm:grid-cols-2 md:mb-8 lg:grid-cols-3 xl:grid-cols-4">
            @foreach (var product in Model.ProductPage.Items)
            {
                @await Component.InvokeAsync("ProductCard", new { product = product, showFeaturedTag = false })
            }
        </div>
        
        @await Component.InvokeAsync("Pagination", new { count = Model.ProductPage.Count, pageNumber = Model.ProductPage.PageNumber, pageSize = Model.ProductPage.PageSize })

    </div>
</section>

RookieShop.FrontStore/Views/Products/ProductsByCategory.cshtml
@model RookieShop.FrontStore.Models.Products.ProductsByCategoryViewModel

@{
    ViewData["Title"] = Model.Category.Name;
}

<section class="bg-gray-50 py-8 antialiased dark:bg-gray-900 md:py-12">
    <div class="mx-auto max-w-screen-xl px-4 2xl:px-0">
        <div class="mb-4 items-end justify-between space-y-4 sm:flex sm:space-y-0 md:mb-8">
            <div>
                <h2 class="mt-3 text-xl font-semibold text-gray-900 dark:text-white sm:text-2xl">@Model.Category.Name</h2>
                <h3 class="mt-3 text-md text-gray-500 dark:text-white">@Model.Category.Description</h3>
            </div>
        </div>
    </div>
</section>

<section class="bg-gray-50 py-8 antialiased dark:bg-gray-900 md:py-12">
    <div class="mx-auto max-w-screen-xl px-4 2xl:px-0">
        <div class="mb-4 items-end justify-between space-y-4 sm:flex sm:space-y-0 md:mb-8">
            <div>
                <h2 class="mt-3 text-xl font-semibold text-gray-900 dark:text-white sm:text-2xl">Products</h2>
            </div>
        </div>

        <div class="mb-4 grid gap-4 sm:grid-cols-2 md:mb-8 lg:grid-cols-3 xl:grid-cols-4">
            @foreach (var product in Model.ProductPage.Items)
            {
                @await Component.InvokeAsync("ProductCard", new { product = product, showFeaturedTag = false })
            }
        </div>

        @await Component.InvokeAsync("Pagination", new { count = Model.ProductPage.Count, pageNumber = Model.ProductPage.PageNumber, pageSize = Model.ProductPage.PageSize })
    </div>
</section>

RookieShop.FrontStore/Views/Products/ProductsSemantic.cshtml
@model RookieShop.FrontStore.Models.Products.ProductsSemanticViewModel

@{
    ViewData["Title"] = "Semantic Search";

    var otherParams = new Dictionary<string, string>
    {
        ["semantic"] = Model.Semantic
    };
}

<section class="bg-gray-50 py-8 antialiased dark:bg-gray-900 md:py-12">
    <div class="mx-auto max-w-screen-xl px-4 2xl:px-0">
        <div class="mb-4 items-end justify-between space-y-4 sm:flex sm:space-y-0 md:mb-8">
            <div>
                <h2 class="mt-3 text-xl font-semibold text-gray-900 dark:text-white sm:text-2xl">Result for "@Model.Semantic"</h2>
            </div>
        </div>

        <div class="mb-4 grid gap-4 sm:grid-cols-2 md:mb-8 lg:grid-cols-3 xl:grid-cols-4">
            @foreach (var product in Model.ProductPage.Items)
            {
                @await Component.InvokeAsync("ProductCard", new { product = product, showFeaturedTag = false })
            }
        </div>

        @await Component.InvokeAsync("Pagination", new { count = Model.ProductPage.Count, pageNumber = Model.ProductPage.PageNumber, pageSize = Model.ProductPage.PageSize, otherParams = otherParams })
    </div>
</section>